// Demo/React/HelloWorld.CRA/src/HelloWorld.js
import React from 'react';
import dotnetify from 'dotnetify';

dotnetify.hubServerUrl = 'http://localhost:5000';

export default class HelloWorld extends React.Component {
	constructor(props) {
		super(props);
		dotnetify.react.connect('HelloWorld', this);
		this.state = { Greetings: '', ServerTime: '' };
	}

	render() {
		return (
			<div>
				<p>{this.state.Greetings}</p>
				<p>Server time is: {this.state.ServerTime}</p>
			</div>
		);
	}
}

// Demo/Vue/HelloWorld.CLI/src/components/HelloWorld.vue
<template>
  <div class="hello">
    <h1>{{ msg }}</h1>
    <div>
      <h3>{{ state.Greetings }}</h3>
      <p>Server time is: {{ state.ServerTime }}</p>
    </div>
  </div>
</template>

<script>
import dotnetify from 'dotnetify/vue';
dotnetify.hubServerUrl = 'http://localhost:5000';

export default {
  props: { msg: String },
  ...dotnetify.vue.component("hello-world", "HelloWorld")
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 { font-weight: 500; }
</style>
