// Demo/Vue/HelloWorld.WebPack/src/HelloWorld.vue
<template>
  <div>
    <p>{{ Greetings }}</p>
    <p>Server time is: {{ ServerTime }}</p>
  </div>
</template>

<script>
import dotnetify from "dotnetify/vue";

export default {
  name: "HelloWorld",
  created: function () {
    this.vm = dotnetify.vue.connect("HelloWorld", this);
  },
  unmounted: function () {
    this.vm.$destroy();
  },
  data: function () {
    return { Greetings: "", ServerTime: "" };
  }
};
</script>

// Demo/React/HelloWorld.WebPack/src/HelloWorld.tsx
import React from 'react';
import dotnetify from 'dotnetify';

interface State {
  Greetings: string;
  ServerTime: string;
}

export class HelloWorld extends React.Component<any, State> {
  state: State = { Greetings: '', ServerTime: '' };

  constructor(props: any) {
    super(props);
    dotnetify.react.connect('HelloWorld', this);
  }

  render() {
    return (
      <div>
        <p>{this.state.Greetings}</p>
        <p>Server time is: {this.state.ServerTime}</p>
      </div>
    );
  }
}
