// DevApp/client/app/views/examples/react/ChatRoom.js
import React from "react";
import dotnetify from "dotnetify";
import TextBox from "../components/TextBox";
import { ChatRoomCss } from "../components/css";

class ChatRoom extends React.Component {
  constructor(props) {
    super(props);
    this.state = { Users: [], Messages: [], message: "" };
    this.scrollToBottom = () =>
      this.bottomElem.scrollIntoView({ behavior: "smooth" });

    this.vm = dotnetify.react.connect("ChatRoomVM", this);
    this.dispatchState = state => this.vm.$dispatch(state);
    this.correlationId = `${Math.random()}`;
  } 

  componentDidUpdate() {
    if (!this.state.Users.some(x => x.CorrelationId == this.correlationId)) {
      this.dispatchState({ AddUser: this.correlationId });
    }

    this.scrollToBottom();
    if (this.state.PrivateMessage) {
      let message = this.state.PrivateMessage;
      message.Text = "(private) " + message.Text;
      message.private = true;
      this.setState({ Messages: this.state.Messages.concat(message) });
      this.setState({ PrivateMessage: null });
    }
  }

  componentWillUnmount() {
    this.dispatchState({ RemoveUser: null });
    this.vm.$destroy();
  }

  getUserName(userId) {
    const user = this.state.Users.find(x => x.Id === userId);
    return user ? user.Name : null;
  }

  sendMessage(text) {
    var match = /name is ([A-z]+)/i.exec(text);
    this.dispatchState({
      SendMessage: {
        Text: text,
        Date: new Date(),
        UserName: match ? match[1] : ""
      }
    });
    this.setState({ message: "" });
  }

  render() {
    return (
      <ChatRoomCss>
        <div className="chatPanel">
          <nav>
            {this.state.Users.map(user => (
              <p key={user.Id}>
                <b
                  className={
                    user.CorrelationId == this.correlationId ? "myself" : ""
                  }
                >
                  {user.Name}
                </b>
                <span>{user.IpAddress}</span>
                <span>{user.Browser}</span>
              </p>
            ))}
          </nav>
          <section>
            <div>
              {this.state.Messages.map((msg, idx) => (
                <div key={idx}>
                  <div>
                    <span>{this.getUserName(msg.UserId) || msg.UserName}</span>
                    <span>{new Date(msg.Date).toLocaleString()}</span>
                  </div>
                  <div className={msg.private ? "private" : ""}>{msg.Text}</div>
                </div>
              ))}
              <div
                style={{ float: "left", clear: "both" }}
                ref={el => (this.bottomElem = el)}
              />
            </div>
            <TextBox
              placeholder="Type your message here"
              value={this.state.message}
              onChange={value => this.setState({ message: value })}
              onUpdate={value => this.sendMessage(value)}
            />
          </section>
        </div>
        <footer>
          <div>* Hint:</div>
          <ul>
            <li>type 'my name is ___' to introduce yourself</li>
            <li>type '&lt;username&gt;: ___' to send private message</li>
          </ul>
        </footer>
      </ChatRoomCss>
    );
  }
}

export default ChatRoom;

// DevApp/client/app/views/examples/vue/ChatRoom.vue
<template>
  <div>
    <div class="chatPanel">
      <nav>
        <p v-for="user in Users" :key="user.Id">
          <b :class="user.CorrelationId == correlationId ? 'myself' : ''">{{ user.Name }}</b>
          <span>{{ user.IpAddress }}</span>
          <span>{{ user.Browser }}</span>
        </p>
      </nav>
      <section>
        <div>
          <div v-for="(msg, idx) in Messages" :key="idx">
            <div>
              <span>{{ getUserName(msg.UserId) || msg.UserName }}</span>
              <span>{{ new Date(msg.Date).toLocaleString() }}</span>
            </div>
            <div :class="msg.private ? 'private' : ''">{{ msg.Text }}</div>
          </div>
        </div>
        <div style="float: left; clear: both;" ref="bottomElem" />
        <input type="text" class="form-control" placeholder="Type your message here" v-model="message" @change="sendMessage" />
      </section>
    </div>
    <footer>
      <div>* Hint:</div>
      <ul>
        <li>type 'my name is ___' to introduce yourself</li>
        <li>type '&lt;username&gt;: ___' to send private message</li>
      </ul>
    </footer>
  </div>
</template>

<script>
export default {
  name: "ChatRoom",
  created() {
    this.vm = dotnetify.vue.connect("ChatRoomVM", this);

    this.$watch("PrivateMessage", message => {
      this.scrollToBottom();
      message.Text = "(private) " + message.Text;
      message.private = true;
      this.Messages.push(message);
      this.PrivateMessage = null;
    });
  },
  mounted() {
    this.scrollToBottom();
  },
  updated() {
    if (!this.Users.some(x => x.CorrelationId == this.correlationId)) {
      this.vm.$dispatch({ AddUser: this.correlationId });
    }
  },
  unmounted() {
    this.vm.$dispatch({ RemoveUser: null });
    this.vm.$destroy();
  },
  data() {
    return {
      Users: [],
      Messages: [],
      PrivateMessage: null,
      message: "",
      correlationId: `${Math.random()}`
    };
  },
  methods: {
    getUserName(userId) {
      const user = this.Users.find(x => x.Id === userId);
      return user ? user.Name : null;
    },
    scrollToBottom() {
      this.$refs.bottomElem.scrollIntoView({ behavior: "smooth" });
    },
    sendMessage() {
      const match = /name is ([A-z]+)/i.exec(this.message);
      this.vm.$dispatch({
        SendMessage: {
          Text: this.message,
          Date: new Date(),
          UserName: match ? match[1] : ""
        }
      });
      this.message = "";
    }
  }
};
</script>
