// DevApp/client/app/views/examples/vue/CompositeView.vue
<template>
  <Scope vm="CompositeViewVM">
    <Scope tag="section" vm="FilterableMovieTableVM">
      <MovieTable/>
    </Scope>
    <aside>
      <MovieDetails/>
      <MovieFilter/>
    </aside>
  </Scope>
</template>

<script>
import dotnetify from 'dotnetify/vue';
import MovieTable from './CompositeView.MovieTable.vue';
import MovieDetails from './CompositeView.MovieDetails.vue';
import MovieFilter from './CompositeView.MovieFilter.vue';

export default {
  name: 'CompositeView',
  components: {
    'Scope': dotnetify.vue.Scope,
    'MovieTable': MovieTable,
    'MovieDetails': MovieDetails,
    'MovieFilter': MovieFilter
  }
}
</script>

// Demo/React/SPA/client/CompositeView/index.js
import React from 'react';
import { Scope } from 'dotnetify';
import { CompositeViewCss } from '../components/css';
import MovieTable from './MovieTable';
import MovieDetails from './MovieDetails';

const CompositeView = () => (
  <CompositeViewCss>
    <Scope vm="CompositeViewVM">
      <MovieTable />
      <aside>
        <MovieDetails />
      </aside>
    </Scope>
  </CompositeViewCss>
);

export default CompositeView;
