// DevApp/client/app/views/examples/vue/HelloWorld.vue
<template>
  <div id="HelloWorld">
    <section>
      <div>
        <label>First name:</label>
        <input type="text" class="form-control" v-model.lazy="FirstName">
      </div>
      <div>
        <label>Last name:</label>
        <input type="text" class="form-control" v-model.lazy="LastName">
      </div>
    </section>
    <div>
      Full name is
      <b>
        <span>{{FullName}}</span>
      </b>
    </div>
  </div>
</template>

<script>
import dotnetify from 'dotnetify/vue';

export default {
  name: 'HelloWorld',
  created: function () {
    this.vm = dotnetify.vue.connect("HelloWorldVM", this, { watch: ['FirstName', 'LastName'] });
  },
  data() {
    return { FirstName: '', LastName: '', FullName: '' }
  }
}
</script>

// DevApp/client/app/views/examples/react/HelloWorld.js
import React from "react";
import { useConnect } from "dotnetify";
import TextBox from "../components/TextBox";
import { HelloWorldCss } from "../components/css";

const HelloWorld = () => {
  const { vm, state, setState } = useConnect("HelloWorldVM");

  return (
    <HelloWorldCss>
      <section>
        <TextBox
          label="First Name:"
          placeholder="Type first name here"
          value={state.FirstName}
          onChange={value => setState({ FirstName: value })}
          onUpdate={value => vm.$dispatch({ FirstName: value })}
        />
        <TextBox
          label="Last Name:"
          placeholder="Type last name here"
          value={state.LastName}
          onChange={value => setState({ LastName: value })}
          onUpdate={value => vm.$dispatch({ LastName: value })}
        />
      </section>
      <div>
        Full name is <b>{state.FullName}</b>
      </div>
    </HelloWorldCss>
  );
};

export default HelloWorld;
