// Demo/React/SPA/client/App.js
import React from 'react';
import dotnetify, { RouteLink } from 'dotnetify';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = { Links: [] };

    this.vm = dotnetify.react.connect('App', this);
    this.vm.onRouteEnter = (path, template) => (template.Target = 'Content');
  }

  componentWillUnmount() {
    this.vm.$destroy();
  }

  render() {
    return (
      <div>
        <nav className="navbar navbar-expand-lg navbar-light bg-light">
          {this.state.Links.map(link => (
            <RouteLink key={link.Id} vm={this.vm} route={link.Route} style={{ paddingRight: '2rem' }}>
              {link.Caption}
            </RouteLink>
          ))}
        </nav>
        <div id="Content" />
      </div>
    );
  }
}

// Demo/Vue/SPA/client/App.vue
<template>
  <div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a
        v-for="link in Links"
        :key="link.Id"
        v-vmRoute="link.Route"
        style="padding-right: 2rem"
      >{{link.Caption}}</a>
    </nav>
    <div id="Content"/>
  </div>
</template>

<script>
import dotnetify from 'dotnetify/vue';

export default {
  created() {
    this.vm = dotnetify.vue.connect('App', this);
    this.vm.onRouteEnter = (path, template) => (template.Target = 'Content');
  },
  destroyed() {
    this.vm.$destroy();
  },
  data() { return { Links: [] } }
}
</script>

<style lang="scss">
.navbar {
  justify-content: left;
}
</style>
