// Demo/React/LazyLoadRouting/src/Views/App.js
import React from 'react';
import dotnetify, { useConnect, RouteLink } from 'dotnetify';
import { lazyLoad } from '../routes';

dotnetify.debug = true;

export default props => {
  const { vm, state } = useConnect('App', { props, state: { Links: [] } });
  if (vm)
    vm.onRouteEnter = (path, template) => {
      template.Target = 'Content';
      return lazyLoad(template.Id);
    };
  return (
    <main>
      <ul>
        {state.Links.map((link, idx) => (
          <li key={idx}>
            <RouteLink vm={vm} route={link.Route}>
              {link.Title}
            </RouteLink>
          </li>
        ))}
      </ul>
      <section id="Content" />
    </main>
  );
};

// Demo/Vue/SPA/client/App.vue
<template>
  <div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a
        v-for="link in Links"
        :key="link.Id"
        v-vmRoute="link.Route"
        style="padding-right: 2rem"
      >{{link.Caption}}</a>
    </nav>
    <div id="Content"/>
  </div>
</template>

<script>
import dotnetify from 'dotnetify/vue';

export default {
  created() {
    this.vm = dotnetify.vue.connect('App', this);
    this.vm.onRouteEnter = (path, template) => (template.Target = 'Content');
  },
  destroyed() {
    this.vm.$destroy();
  },
  data() { return { Links: [] } }
}
</script>

<style lang="scss">
.navbar {
  justify-content: left;
}
</style>
